
- name: Kubesphere | Creating redis migration script
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/{{ item.file }}"
  with_items:
    - { path: /etc/kubesphere, file: redisMigrate.py }


- name: Kubesphere | Check redis-ha status
  shell: >
    {{ bin_dir }}/kubectl get pod -n kubesphere-system | grep 'redis-ha' | grep -v 'Running' | wc -l
  register: import
  until: import.stdout == "0"
  retries: 30
  delay: 30


- name: ks-logging | Migrating redis data
  shell: >
    chmod +x {{ kubesphere_dir }}/redisMigrate.py &&
    {{ kubesphere_dir }}/redisMigrate.py


- name: Kubesphere | Disable old redis
  shell: >
    {{ bin_dir }}/kubectl -n kubesphere-system scale deployment redis --replicas=0