- name: istio | Check jaeger-operator
  shell: >
    {{ bin_dir }}/helm list -n istio-system | grep "jaeger-operator"
  register: jaeger_check
  failed_when: false

- name: istio | Delete jaeger-operator deployment
  shell: >
    {{ bin_dir }}/kubectl delete deploy -n istio-system jaeger-operator
  when:
    - (jaeger_check.stdout.find("deployed") != -1) and (jaeger_check.stdout.find("1.17.1") == -1)
  ignore_errors: True

- name: istio | Deploy jaeger-operator
  shell: >
    {{ bin_dir }}/helm upgrade --install jaeger-operator {{ kubesphere_dir }}/istio/jaeger-operator
    -f {{ kubesphere_dir }}/istio/custom-values-jaeger.yaml
    --namespace istio-system
  when:
    - (jaeger_check.stdout.find("deployed") == -1) or (jaeger_check.stdout.find("1.17.1") == -1)

- name: istio | Deploy jaeger-production
  shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/istio/jaeger-production.yaml --namespace istio-system"
  register: import
  until: import is succeeded
  retries: 5
  delay: 10
  when:
    - (jaeger_check.stdout.find("deployed") == -1) or (jaeger_check.stdout.find("1.17.1") == -1)

- name: istio | Create jaeger operator service
  shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/istio/jaeger-operator-service.yaml --namespace istio-system"
  register: import
  until: import is succeeded
  retries: 5
  delay: 10
  when:
    - (jaeger_check.stdout.find("deployed") == -1) or (jaeger_check.stdout.find("1.17.1") == -1)
